# Generated by Django 5.1.6 on 2025-03-03 07:55

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ_donor.category')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('organ_type', models.CharField(choices=[('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Pancreas', 'Pancreas'), ('Small Intestine', 'Small Intestine'), ('Eyes', 'Eyes')], max_length=50)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('is_available', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='D.O.B')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('medical_report', models.ImageField(upload_to='medical_reports/')),
                ('witness_name', models.CharField(max_length=100, verbose_name='Witness Name')),
                ('witness_whatsappNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('whatsappNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('diseases', models.ManyToManyField(blank=True, to='organ_donor.diseases')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('organ_type', models.CharField(choices=[('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Pancreas', 'Pancreas'), ('Small Intestine', 'Small Intestine'), ('Eyes', 'Eyes')], max_length=50)),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('is_available', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='D.O.B')),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('medical_report', models.ImageField(upload_to='medical_reports/')),
                ('witness_name', models.CharField(max_length=100, verbose_name='Witness Name')),
                ('witness_whatsappNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Contact Number')),
                ('whatsappNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('diseases', models.ManyToManyField(blank=True, to='organ_donor.diseases')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
